apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rabbitmq.yaml
  - rabbitmq-pvc.yaml
  - rabbitmq-config.yaml

configMapGenerator:
  - name: rabbitmq-definitions
    behavior: merge
    envs:
      - .env 