apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_management_agent].
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    management.load_definitions = /etc/rabbitmq/definitions.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
data:
  definitions.json: |
    {
      "users": [
        {
          "name": "${RABBITMQ_USER}",
          "password": "${RABBITMQ_PASSWORD}",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "${RABBITMQ_USER}",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    } 