apiVersion: v1
kind: ConfigMap
metadata:
  name: task-api-config
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "user"
  RABBITMQ_PASSWORD: "password" 